name: 'Composer Install'
description: 'Do composer install'

runs:
  using: composite
  steps:
    - uses: actions/cache@v3
      with:
        path: web/vendor
        key: composer-${{ hashFiles('composer.lock') }}

    - name: Install Composer Dependencies
      run: composer install -q --no-ansi --no-interaction --no-progress --prefer-dist --ignore-platform-reqs
      shell: bash
