name: 'Prepare database'
description: 'Prepare mysql'

runs:
  using: composite
  steps:
    - name: Create Database
      run: |
        sudo systemctl start mysql
        mysql --user="root" --password="root" -e "CREATE DATABASE \`laravel\` character set UTF8mb4 collate utf8mb4_bin;"
      shell: bash
