name: 'goodmoments.tw'

cache_path: '.licensed/'

composer:
  application_path: '/usr/bin/composer'

allowed:
  - mit
  - lgpl-2.1
  - apache-2.0
  - bsd-2-clause
  - bsd-3-clause
  - cc0-1.0
  - isc
